{{- if eq .Values.app.cronjob.cleanusers.launch true }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: phraseanet-cronjob-cleanuser
spec:
  schedule: {{ .Values.app.cronjob.cleanusers.cron  }}
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: phraseanet-config
            persistentVolumeClaim:
              claimName: {{ .Values.app.pvc_name.config }}
          - name: phraseanet-datas
            persistentVolumeClaim:
              claimName: {{ .Values.app.pvc_name.data }}
          - name: phraseanet-thumbnails
            persistentVolumeClaim:
              claimName: {{ .Values.app.pvc_name.thumbnails }}
          - name: phraseanet-custom
            persistentVolumeClaim:
              claimName: {{ .Values.app.pvc_name.custom }}
          - name: phraseanet-tmp
            emptyDir:
          - name: phraseanet-logs
            emptyDir:
          - name: phraseanet-cache
            emptyDir:
          - name: phraseanet-ftp
            persistentVolumeClaim:
              claimName: {{ .Values.app.pvc.ftp.name }}
          - name: phraseanet-backup
            persistentVolumeClaim:
              claimName: {{ .Values.app.pvc.backup.name }}
          containers:
          - name: phraseanet-cronjob-cleanuser
            image: {{ .Values.image.registry }}/phraseanet-worker:{{ .Values.image.tag.phraseanet }}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - date; echo Hello from the Kubernetes cluster; df -h; {{ .Values.app.cronjob.cleanusers.cmd  }}
            volumeMounts:
              - name: phraseanet-config
                mountPath: "/var/alchemy/Phraseanet/config"
              - name: phraseanet-datas
                mountPath: "/var/alchemy/Phraseanet/datas"
              - name: phraseanet-tmp
                mountPath: "/var/alchemy/Phraseanet/tmp"
              - name: phraseanet-logs
                mountPath: "/var/alchemy/Phraseanet/logs"
              - name: phraseanet-thumbnails
                mountPath: "/var/alchemy/Phraseanet/www/thumbnails"
              - name: phraseanet-custom
                mountPath: "/var/alchemy/Phraseanet/www/custom"
              - name: phraseanet-cache
                mountPath: "/var/alchemy/Phraseanet/cache"  
              - name: phraseanet-ftp
                mountPath: "/var/alchemy/Phraseanet/ftp"
              - name: phraseanet-backup
                mountPath: "/var/alchemy/Phraseanet/backup" 
            env:
            - name: PHP_LOG_LEVEL
              value: {{ .Values.php.log_level | quote }}
            - name: SESSION_CACHE_LIMITER
              value: {{ .Values.php.session_cache_limiter | quote }}
            - name: SESSION_SAVE_HANDLER
              value: {{ .Values.php.session_save_handler | quote }}
            - name: SESSION_SAVE_PATH
              value: {{ .Values.php.session_save_path | quote }}
            - name: XDEBUG
              value: "0"
            - name: NEWRELIC_ENABLED
              value: {{ .Values.php.newrelic_enabled | quote }}
            - name: NEWRELIC_LICENSE_KEY
              value: {{ .Values.php.newrelic_licence_key | quote }}
            - name: NEWRELIC_APP_NAME
              value: {{ .Values.php.newrelic_app_name | quote }}
            - name: LC_MESSAGES
              value: "C.UTF-8"
            - name: LC_COLLATE
              value: "C.UTF-8"
            - name: LC_IDENTIFICATION
              value: "C.UTF-8"
            - name: LANG
              value: "C.UTF-8"
            - name: LC_MEASUREMENT
              value: "C.UTF-8"
            - name: LC_CTYPE
              value: "C.UTF-8"
            - name: LC_TIME
              value: "C.UTF-8"
            - name: LC_NAME
              value: "C.UTF-8"  
          restartPolicy: OnFailure

{{- end }}