{{- if eq .Values.app.hpa.records.enabled true }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-records
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: phraseanet-worker-records
  minReplicas: {{ .Values.app.hpa.records.minReplicas }}
  maxReplicas: {{ .Values.app.hpa.records.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.app.hpa.records.averageUtilization }}
{{- end }}