{{- if eq .Values.app.hpa.subdefcreation.started true }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-subdefcreation
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-subdefcreation
  minReplicas: {{ .Values.app.hpa.subdefcreation.minReplicas }}
  maxReplicas: {{ .Values.app.hpa.subdefcreation.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.app.hpa.subdefcreation.averageUtilization }}
{{- end }}