{{- if eq .Values.app.hpa.exportemail.started true }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-exportemail
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-exportemail
  minReplicas: {{ .Values.app.hpa.exportemail.minReplicas }}
  maxReplicas: {{ .Values.app.hpa.exportemail.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.app.hpa.exportemail.averageUtilization }}
{{- end }}