{{- if eq .Values.saml.enabled true }}
{{- if eq .Values.saml.saml_secret.enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.phraeanet_hostname }}-saml-secret
type: Opaque
data:
   {{- range $key, $val := .Values.saml.saml_secrets.all }}
     {{ $key }}: {{ $val | b64enc | quote }}
   {{- end }}
{{- end }}
{{- end }}